
on:
  push:

jobs:
  upload:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - module: feedparser
            index: first
          - module: aws-cloudwatch-logs-url
            index: second
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: 3.13
      - run: pip install ${{ matrix.module }} -t python/${{ matrix.module }}
      - uses: actions/upload-artifact@v4
        with:
          name: modules-${{ matrix.index }}
          path: python

  check:
    runs-on: ubuntu-latest
    needs:
      - upload
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: modules-*
          merge-multiple: true
      - run: find . | sort
